POST http://localhost:3003/api/blogs
Content-Type: application/json

{
      "title": "Pallopanoraamablogi",
      "author": "Janne",
      "url": "pallopanoramablogi.blogpost.com",      
      "likes": 3
}

###
GET http://localhost:3003/api/blogs

###
DELETE http://localhost:3003/api/blogs/645bae8e5620ad8783c66325

###
PUT http://localhost:3003/api/blogs/645bc852a974f5354695a57c
Content-Type: application/json

{
      "title": "Pallopanoraamablogi",
      "author": "Janne",
      "url": "pallopanoramablogi.blogpost.com",      
      "likes": 5
}

### Users
POST http://localhost:3003/api/users
Content-Type: application/json

{
      "name": "Jari",
      "username": "jzray",
      "password": "salasana"
}
