POST http://localhost:3003/api/users
Content-Type: application/json

{
      "name": "Jari",
      "username": "jzray6",
      "password": "salasana"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
      "name": "Jari",
      "username": "jzray7",
      "password": "salasana"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
      "name": "Jari",
      "password": "salasana"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
      "name": "Jari",
      "username": "jzray"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
      "name": "Jari",
      "username": "jzray",
      "password": "sa"
}

###LOGIN
POST http://localhost:3003/api/login
Content-Type: application/json

{
      "username": "jzray7",
      "password": "salasana"
}

###virheellinen
POST http://localhost:3003/api/login
Content-Type: application/json

{
      "username": "jzray6",
      "password": "vaara_salasana"
}
###virheellinen
POST http://localhost:3003/api/login
Content-Type: application/json

{
      "username": "vaara_jzray",
      "password": "salasana"
}