POST http://localhost:3001/api/persons
Content-Type: application/json

{
      "name": "Erkki Junkkarinen",
      "number": "90 82237" 
}

########

POST http://localhost:3001/api/persons
Content-Type: application/json

{
      "name": "Erkki Junkkarinen"
}

########

POST http://localhost:3001/api/persons
Content-Type: application/json

{
      "number": "90 82237" 
}